#!/bin/bash
# sysinfo_page  - A script to communicate with Oblique backend and create shortened URLs.

## Useless show off
cat << "EOF"
________ ___.   .__  .__                      
\_____  \\_ |__ |  | |__| ________ __   ____  
 /   |   \| __ \|  | |  |/ ____/  |  \_/ __ \ 
/    |    \ \_\ \  |_|  < <_|  |  |  /\  ___/ 
\_______  /___  /____/__|\__   |____/  \___  >
        \/    \/            |__|           \/ 
================================================
Developer : Prashant Shrestha (www.prashant.me)
================================================

EOF

## Arguments
URLTOSHORTEN=""
SHORTED=""
BASE_URL="http://mybox:1338/short" # mybox refers to my server's IP address.
AUTH_KEY=""
validurlregex='(https?|ftp|file)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]'

## Start
## Check if the URL is provided in a parameter.
PARAMLINK=$1

if [ ${#PARAMLINK} -ge 30 ]; then
    URLTOSHORTEN=$PARAMLINK
else
    ## Prompt for long URL if not provided.
    echo "Please enter the long URL that you wish to shorten."
    read URLTOSHORTEN
fi

if [ ${#URLTOSHORTEN} -ge 30 ]; then
	## Check if the provided URL is a valid URL.
	if [[ $URLTOSHORTEN =~ $validurlregex ]]; then
		## Seems valid, let's shorten the URL.
        RESP=$(curl -s -d "auth=$AUTH_KEY&link=$URLTOSHORTEN" -X POST $BASE_URL) || exit
		MODD="${RESP/o.prashant.me/shorted.tk}"

        if [[ $MODD =~ '"shortened"' ]]; then
            SHORTED=$(echo $MODD | jq ".shortened")
        elif [[ $MODD =~ '"link"' ]]; then
            SHORTED=$(echo $MODD | jq ".link")
        else
            echo $MODD
        fi
		echo $SHORTED
		echo $SHORTED | tr -d '\n"' | xclip -sel clip
	else
		echo "Please provide a valid URL!"
	fi
else
    echo "Sorry but, you are joking right?"
fi
